### ISSUE TITLE
withdraw telegram消息处理异常

### ISSUE THREAD

**Issue by tanlentboy** [zhangpanyi/botcasino#16]
@zhangpanyi，报告个问题：红包提现到最后一步确认提现的时候，消息处理一直处于 loading 状态。这个是telegram消息处理出现问题吗？

**Comment by zhangpanyi** [comment]
点击确认提现的时候一直loading嘛?

**Comment by tanlentboy** [comment]
是的。点击确认提现的时候，telegram顶部消息状态一直显示loading，非正常状态。@luck_money_bot.

**Comment by tanlentboy** [comment]
张老师有tg交流群吗我想加入讨论，😄

**Comment by zhangpanyi** [comment]
我测试了一下没出现这个问题，你现在看看还有吗。tg现在暂时没有交流群，你可以加我tg：https://t.me/byteone

**Comment by tanlentboy** [comment]
@zhangpanyi  还是有问题。提现卡在第四步 确认提现的地方。
我弄个软件tg 录频给你瞧瞧
