### ISSUE TITLE
红包测试机器人没反应

### ISSUE THREAD

**Issue by tanlentboy** [zhangpanyi/botcasino#6]
张老师，TG红包机器人是个很精彩的应用。利用bts去中心化和bitcny或者bitusd 的方式发红包是个非常有趣的想法，测试机器人没有运行吗？添加之后没反应，是不是我唤醒命令不对的原因？ @luck_money_bot

**Comment by zhangpanyi** [comment]
服务器到期了，最近两天会重启

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zhangpanyi** [comment]
已恢复
